name: plenr

services:
  plenr:
    image: tomashula/plenr
    ports:
      - "127.0.0.1:8080:80"
    environment:
        "config.override.server.url": http://localhost:8080/
        "config.override.server.host": 0.0.0.0
        "config.override.server.port": 80
        "config.override.database.url": jdbc:mysql://mysql:3306/plenr
        "config.override.database.user": plenr
        "config.override.database.password": plenr
        "config.override.smtp.host": mailhog
        "config.override.smtp.port": 1025

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_USER: plenr
      MYSQL_DATABASE: plenr
      MYSQL_PASSWORD: plenr
      MYSQL_RANDOM_ROOT_PASSWORD: yes

  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8025:8025"